## name: Black Metal Venom Extended (Darker Red)
## author: Britton Petersen
## inspired_by: Welcome to Hell (1981)
## license: MIT

# Core colors
background            #000000
foreground            #c1c1c1
selection_background  #5f8787
selection_foreground  #000000
cursor                #f8f7f2
cursor_text_color     #000000
url_color             #5f8787

# Tabs
active_tab_background   #5f8787
active_tab_foreground   #000000
inactive_tab_background #211816
inactive_tab_foreground #888888
tab_bar_background      #000000

# Windows
active_border_color     #c72a28
inactive_border_color   #211816
bell_border_color       #c72a28

# normal ANSI colors
color0  #000000
color1  #c72a28
color2  #6e4c4c
color3  #aaaaaa
color4  #5f8787
color5  #9b99a3
color6  #888888
color7  #c1c1c1

# bright ANSI colors
color8   #333333
color9   #c72a28
color10  #6e4c4c
color11  #f8f7f2
color12  #5f8787
color13  #9b99a3
color14  #888888
color15  #c1c1c1

# extended ANSI colors
color16 #a0663d
color17 #957fbb
color18 #1f1f28
color19 #d9b865
color20 #505050
color21 #7f7f7f
color22 #98bb6c
color23 #496868
color24 #8f1f1d
color25 #c8c8c8

# Other
dim_foreground_color  #505050

# vim:ft=kitty

