## name: Black Metal Venom
## author: Britton Petersen
## inspired_by: Welcome to Hell (1981)
## license: MIT

# Core colors
background            #000000
foreground            #c1c1c1
selection_background  #5f8787
selection_foreground  #000000
cursor                #f8f7f2
cursor_text_color     #000000
url_color             #5f8787

# Tabs
active_tab_background   #5f8787
active_tab_foreground   #000000
inactive_tab_background #211816
inactive_tab_foreground #888888
tab_bar_background      #000000

# Windows
active_border_color     #5f8787
inactive_border_color   #211816
bell_border_color       #fc302e

# normal
color0  #000000
color1  #fc302e
color2  #6e4c4c
color3  #aaaaaa
color4  #999999
color5  #9b99a3
color6  #888888
color7  #c1c1c1

# bright
color8   #333333
color9   #fc302e
color10  #6e4c4c
color11  #f8f7f2
color12  #999999
color13  #9b99a3
color14  #888888
color15  #f8f7f2

# extended (optional extra colors for plugins/ls etc.)
color16 #5f8787
color17 #fc302e

# Other
dim_foreground_color  #505050

# vim:ft=kitty

